import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './style.css';
import Nav from '@/components/Navbar/Nav';
import Footer from '@/components/Footer/Footer';
import ProviderStore from './ProviderStore';
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'You Success',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto max-w-screen-lg">
          <ProviderStore>
            <Nav />
            {children}
            <Footer />
          </ProviderStore>
        </div>
      </body>
    </html>
  );
}