import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './style.css'
import Nav from "@/components/Navbar/Nav";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "You Success",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto max-w-screen-lg">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
